version: '3.9'
name: 'ivbo'

services:
  #front:
  #  build: ./frontend
  #  restart: always
  #  ports:
  #    - "3005:3000"
  back:
    build: ./backend
    ports:
      - "8083:80"
    depends_on:
      - redis_ivbo
  cache:
    image: "redis:alpine"
    command: redis-server
    ports:
     - "6380:6379"
networks:
  default:
    name: docker_default
    external: true
